# -*- python -*-
Import("env")
import glob, os

# No C++ currently 
# for src in glob.glob("*.cc"):
#     env.Program(src, LIBS=env.getlibs(env["eups_product"]))

#
# Tests
#
# print env.Dump()  # dump whole env
Import("env")
env.Program(["testTracingLog.cc"], LIBS=env.libs["pex_harness"])

env.CheckSwig("python", ilang="c++")
env.Append(SWIGFLAGS=" -Ipython")

import lsst.tests
tests = lsst.tests.Control(env, verbose = True)

tests.run("testTracingLog.cc")

pytstsrps = filter(lambda a: not a.startswith("TestIO_") or a[7] not in "2 3 4".split(), 
                   filter(lambda t: t.startswith("Test") and t.endswith(".py"),
                          os.listdir(".")))
for target in pytstsrps:
    env.Depends(tests.run(target), "../python/lsst/pex/harness/_harnessLib%s" % env['LDMODULESUFFIX'])

