# -*- python -*-
Import("env")
import glob, os

# No C++ currently 
# for src in glob.glob("*.cc"):
#     env.Program(src, LIBS=env.getlibs(env["eups_product"]))

#
# Tests
#
# print env.Dump()  # dump whole env
Import("env")
env.Program(["testTracingLog.cc"], LIBS=env.libs["pex_harness"])

env.CheckSwig("python", ilang="c++")
env.Append(SWIGFLAGS=" -Ipython")

import lsst.tests
tests = lsst.tests.Control(env, verbose = True)

tests.run("testTracingLog.cc")

pytstsrps = filter(lambda t: t.startswith("Test") and t.endswith(".py"),
        os.listdir("."))
if "AFW_DIR" not in os.environ:
    print >>sys.stderr, "afw is not setup, skipping TestIO_[234].py"
    pytstsrps = filter(lambda a: not a.startswith("TestIO_")
            or a[7] not in "2 3 4".split(), pytstsrps)

#pytstsrps += filter(lambda t: t.startswith("test") and t.endswith(".py"),
#                    os.listdir("."))
pytstsrps.append("testDataset.py")
for target in pytstsrps:
    env.Depends(tests.run(target), "../python/lsst/pex/harness/_harnessLib%s" % env['LDMODULESUFFIX'])

