# -*- python -*-
Import("env")

sdir = "../../../../src/"

env.Append(SWIGFLAGS=["-c++", "-python", "-Iinclude"])

env.LoadableModuleIncomplete("_pipeline", Split("Pipeline.i"), LIBS=["dps"])  

env.LoadableModuleIncomplete("_slice", Split("Slice.i"), LIBS=["dps"])  

