# -*- python -*-
Import("env")

dict = env.Dictionary()
ENV  =  dict['ENV']
pwd = ENV['PWD']
print "pwd is %s " % pwd

mpichdir = '/home/ncsa/daues/mpich2/install_gcc3.2'

incdir = pwd + "/include"
sdir = pwd + "/src/"

pydir = ENV['PYTHON_DIR']

print "CPPPATH %s " % env['CPPPATH']
print "pydir %s " % pydir

pyincdir =  pydir + "/include/python2.5"

env.Replace(CPPPATH = env['CPPPATH'] + ":" + incdir + ":" + pyincdir)

print "CPPPATH %s " % env['CPPPATH']

env.SharedLibrary('pipeline', ["Pipeline.i", sdir+"Pipeline.cc", sdir+"Queue.cc", sdir+"Stage.cc", sdir+"Clipboard.cc"], 
                 CXXFLAGS=["-DMPICH_IGNORE_CXX_SEEK"], 
                 SHLIBPREFIX=["_"],
                 SWIGFLAGS=["-c++", "-python", "-Iinclude"])

env.SharedLibrary('slice', ["Slice.i", sdir+"Slice.cc", sdir+"Queue.cc", sdir+"Stage.cc", sdir+"Clipboard.cc"], 
                 CXXFLAGS=["-DMPICH_IGNORE_CXX_SEEK"], 
                 SHLIBPREFIX=["_"],
                 SWIGFLAGS=["-c++", "-python", "-Iinclude"])


