# -*- python -*-
Import("env")

dict = env.Dictionary()
ENV  =  dict['ENV']
pwd = ENV['PWD']
print "pwd is %s " % pwd

# MPICH still need to be integrated into software stack 
mpichdir = '/home/ncsa/daues/mpich2/install_gcc3.2'

# Build Pipeline
env.Object(['Pipeline.cc', 'Clipboard.cc', 'Stage.cc', 'Queue.cc'], LIBS=['mpich'], LIBPATH=mpichdir + '/lib')

# Build Slice
env.Object(['Slice.cc', 'Clipboard.cc', 'Stage.cc', 'Queue.cc'], LIBS=['mpich'], LIBPATH=mpichdir + '/lib')

incdir = pwd + "/include"

pydir = ENV['PYTHON_DIR']

print "CPPPATH %s " % env['CPPPATH']
print "pydir %s " % pydir

pyincdir =  pydir + "/include/python2.5"

env.Replace(CPPPATH = env['CPPPATH'] + ":" + incdir + ":" + pyincdir)

print "CPPPATH %s " % env['CPPPATH']

