# -*- python -*-
Import("env")

env.CheckSwig("python", ilang="c++", includedProducts="utils")
basicLibs = "daf_base pex_exceptions pex_logging pex_policy".split()

env.LoadableModuleIncomplete("_harnessLib", Split("harnessLib.i"), LIBS=basicLibs + ["pex_harness"])  

