# -*- python -*-

Import("env")

dict = env.Dictionary()
ENV  =  dict['ENV']
pwd = ENV['PWD']
print "pwd is %s " % pwd

Import('env')

env.SharedLibrary('dps', map(lambda str: "../src/" + str,
                          ["Pipeline.cc", 
                           "Slice.cc", 
                           "Queue.cc", 
                           "Stage.cc", 
                           "Clipboard.cc"]), 
                            CXXFLAGS=["-DMPICH_IGNORE_CXX_SEEK"], SHLIBPREFIX=["lib"])

