# -*- python -*-

Import("env")

env.Replace(SHLIBPREFIX=["lib"]);

env.SharedLibrary('dps', map(lambda str: "../src/" + str,
                          ["Pipeline.cc", 
                           "Slice.cc", 
                           "Queue.cc", 
                           "Stage.cc", 
                           "Clipboard.cc"]))

